In [1]:
import numpy as np

In [2]:
a=[[0,2,5],[9,-1,29],[0,34,7]]
b=[[3,2,1],[-1,-2,-3],[2,1,-1]]

In [5]:
import numpy as np
from scipy.signal import convolve2d

A = np.array([[0, 2, 5], [9, -1, 29], [0, 34, 7]])
B = np.array([[3, 2, 1], [-1, -2, -3], [2, 1, -1]])

result = convolve2d(A, B)  # 'full', 'valid', or 'same' as per need
print(result)


[[  0   6  19  12   5]
 [ 27  13  85  41  14]
 [ -9  89  47  -4 -85]
 [ 18 -27 -27 -86 -50]
 [  0  68  48 -27  -7]]
