In [ ]:
import tensorflow as  tf

In [ ]:
zero_d=tf.constant(5)
print(zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
one_d=tf.constant([1,23,4,6,86])
print(one_d)

tf.Tensor([ 1 23  4  6 86], shape=(5,), dtype=int32)


In [ ]:
one_d=tf.constant([1,-23,86,97])
print(one_d)

tf.Tensor([  1 -23  86  97], shape=(4,), dtype=int32)


In [ ]:
one_d=tf.constant([1,23,1.4,6,86])
print(one_d)

tf.Tensor([ 1.  23.   1.4  6.  86. ], shape=(5,), dtype=float32)


In [ ]:
## several one-d  tensors  combine to  form two-d tensors
two_d=tf.constant(
    [[1,2,3,4],
     [6,7,8,9]]
)
print(two_d)

tf.Tensor(
[[1 2 3 4]
 [6 7 8 9]], shape=(2, 4), dtype=int32)


In [ ]:
## several two-d  tensors  combine to  form three-d tensors
three_d=tf.constant([
    [[1,2,3,4],
     [6,7,8,9]],
    [[6,8,4,1],
     [7,8,7,2]]
]
)
print(three_d)

tf.Tensor(
[[[1 2 3 4]
  [6 7 8 9]]

 [[6 8 4 1]
  [7 8 7 2]]], shape=(2, 2, 4), dtype=int32)


**Methods of Declaring Tensors**


1.   Using Constant
2.   Using numpy
3.   Using Random Values
4.   Tensors with Specific Values
5.   Identity and Diagonal Tensors
6.   Using Sequences
7.   Tensor Transformations
8.   Ragged Tensors
9.   Sparse Tensors
10.  Initialization from Existing Data




**Using numpy**

In [ ]:
import numpy as np
check=np.array([[1,2,3,4],[6,7,8,9]])
# print(check.dtype)
check

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
## now convert it into tensors
convert_to_tensor=tf.convert_to_tensor(check)
convert_to_tensor

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [6, 7, 8, 9]])>

**Using Random Values**

In [ ]:
randomVal=tf.random.uniform([2,4],maxval=10, dtype=tf.int32)
randomVal

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 9, 1, 3],
       [2, 8, 3, 3]], dtype=int32)>

In [ ]:
tensor = tf.random.normal([2, 3], mean=0, stddev=1)
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.84870386,  0.70013887,  0.34830484],
       [-0.0049282 , -1.0184722 , -0.893198  ]], dtype=float32)>

**Tensors with specific value**

In [ ]:
zero_d=tf.zeros([2,3])
zero_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
one_d=tf.ones([2,3])
one_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
fill_d=tf.fill([4,4],7)
fill_d

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int32)>

In [ ]:
tensorwithRange = tf.range(0, 10, 2)
tensorwithRange

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

**Identify diagonal**

In [ ]:
dia=tf.eye(3)
dia

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
# tf.linalg.diag(): Tensor with specified diagonal values
specifieddiagonalvalues=tf.linalg.diag([1,2,3])
specifieddiagonalvalues

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int32)>

**Using Sequance**


In [ ]:
# tf.linspace(): Linearly spaced values between a start and an end point.
tensor = tf.linspace(0.0, 10.0, num=5)
tensor

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)>

**Tensor Transformations**

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped = tf.reshape(tensor, [3, 2])
print(tensor)
print(reshaped)
# reshaped3=tf.reshape(tensor,[3,3])
# print(reshaped3)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
transposed = tf.transpose(tensor)
print(tensor)
print(transposed)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


**Ragged Tensors**

In [ ]:
# tf.ragged.constant(): Tensor with variable-length inner dimensions
tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
tensor


<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>

**Sparse Tensors**
1. tf.sparse.SparseTensor(): Tensor with mostly zero values

In [ ]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
sparse_tensor


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))