In [52]:
##create 4-D tensors
import tensorflow as tf
three_d_tensors = tf.constant([[[[1,2,3,4,5,6],[1,2,3,4,5,7]],[[1,2,3,4,5,9],[1,2,3,4,5,10]]],[[[1,2,3,4,5,6],[1,2,3,4,5,7]],[[1,2,3,4,5,9],[1,2,3,4,5,10]]]])
print(three_d_tensors)


tf.Tensor(
[[[[ 1  2  3  4  5  6]
   [ 1  2  3  4  5  7]]

  [[ 1  2  3  4  5  9]
   [ 1  2  3  4  5 10]]]


 [[[ 1  2  3  4  5  6]
   [ 1  2  3  4  5  7]]

  [[ 1  2  3  4  5  9]
   [ 1  2  3  4  5 10]]]], shape=(2, 2, 2, 6), dtype=int32)


### Eye
- Construct an identity matrix, or a batch of matrices.

In [53]:
eyeTensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eyeTensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [54]:
tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [55]:
eyeTensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=(3,),
    dtype=tf.dtypes.float32,
    name=None
)
print(eyeTensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [56]:
eyeTensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=(4,2),
    dtype=tf.dtypes.float32,
    name=None
)
print(eyeTensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(4, 2, 3, 3), dtype=float32)


In [57]:
eyeTensor_5d = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=(5, 3,2),
    dtype=tf.dtypes.float32,
    name=None
)
print(eyeTensor_5d)

tf.Tensor(
[[[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 

In [58]:
eyeTensor_5d = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=(5, 3, 2),
    dtype=tf.dtypes.float32,
    name='5d'
)
print(eyeTensor_5d)

tf.Tensor(
[[[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]]



 [[[[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]

   [[1. 0. 0.]
    [0. 1. 0.]
    [0. 0. 1.]]]


  [[[1. 0. 0.]
    [0. 

### Fill
- Creates a tensor filled with a scalar value.

In [59]:
fillTensor=tf.fill(
    dims=[2,4], value=9, name=None, layout=None
)
fillTensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)>

In [60]:
import tensorflow as tf
print(tf.__version__)

2.18.0


## Tensors with specific values
- zeros
- ones
- zeros_like
- ones_like

In [61]:
zero_dim=tf.zeros([2,6],tf.float32)
zero_dim

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

- When you have an existing tensor and want to create another tensor with the same shape and optionally the same or a different data type

In [62]:
orignalTensor=tf.constant([[[1,2,3], [4,5,6]],[[6,7,8],[9,10,11]]])
print(orignalTensor)
zeros_lik=tf.zeros_like(orignalTensor)
print(zeros_lik)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(2, 2, 3), dtype=int32)


- ones and ones_like

In [63]:
onesTensor=tf.ones([3,4], dtype=tf.int32)
onesTensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [64]:
##ones_like
origanl_like=tf.constant([[1,3,8],[1,2,1]])
ones_like=tf.ones_like(origanl_like)
print(origanl_like)
print(ones_like)

tf.Tensor(
[[1 3 8]
 [1 2 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


- shape

In [65]:
shapeofTensor=tf.shape(orignalTensor)
shapeofTensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>

- rank

In [66]:
rankofTensor=tf.rank(orignalTensor)
rankofTensor

<tf.Tensor: shape=(), dtype=int32, numpy=3>

- size

In [67]:
sizeofTensor=tf.size(orignalTensor)
sizeofTensor

<tf.Tensor: shape=(), dtype=int32, numpy=12>

- random.normal
- (output  random variable from a normal distribution)
- [Probability Playgorund for demonstration](https://www.acsu.buffalo.edu/~adamcunn/probability/normal.html)



In [68]:
randomNormal=tf.random.normal(shape=[4,4], mean=6, stddev=2.5, dtype=tf.float32)
randomNormal

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 2.8985982, 10.05975  , 11.844283 ,  5.01675  ],
       [ 5.2003436,  4.5531597,  9.529091 ,  6.539132 ],
       [ 5.0884   ,  4.447166 ,  9.686844 ,  8.696581 ],
       [ 1.7559247,  1.5903668,  4.8026075,  9.673285 ]], dtype=float32)>

In [69]:
randomNormal = tf.random.normal(
    shape=[4, 4], mean=0, stddev=1, dtype=tf.float32)
randomNormal

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.26303658, -1.1443406 , -0.8058413 , -0.73540556],
       [ 0.56451166, -0.91590625, -1.7288088 , -0.34491003],
       [ 0.34803656, -1.0401156 ,  0.6399822 ,  0.6623956 ],
       [ 1.2296424 , -0.05659237,  0.1577653 , -2.0245996 ]],
      dtype=float32)>

- uniform distribution
- Outputs random values from a uniform distribution.
- [Random seed documentation](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)
- [Probablity playgorund uniform distribution](https://www.acsu.buffalo.edu/~adamcunn/probability/uniform.html)


In [70]:
uniformTensor=tf.random.uniform(
    [3,4],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
uniformTensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.39864278, 0.26447988, 0.48921978, 0.4829476 ],
       [0.9550551 , 0.20790255, 0.86026704, 0.59308374],
       [0.22122741, 0.2750126 , 0.95550156, 0.10000169]], dtype=float32)>

In [71]:
uniformTensor = tf.random.uniform(
    [3, 4],
    minval=0,
    maxval=5,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
uniformTensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.5624285 , 4.353036  , 1.7336094 , 2.2332935 ],
       [1.6068149 , 2.5753593 , 0.02889872, 0.9798908 ],
       [4.7639666 , 0.95997214, 3.9297538 , 3.1661904 ]], dtype=float32)>

In [72]:
uniformTensor = tf.random.uniform(
    [3, 4],
    minval=0,
    maxval=5,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
uniformTensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[3, 3, 3, 3],
       [3, 4, 0, 4],
       [3, 4, 1, 0]], dtype=int32)>

In [73]:
tf.random.set_seed(5)
print(tf.random.uniform([3,],minval=0,maxval=10,dtype=tf.int32,seed=10))
print(tf.random.uniform([3,],minval=0,maxval=10,dtype=tf.int32,seed=10))
print(tf.random.uniform([3,],minval=0,maxval=10,dtype=tf.int32,seed=10))
print(tf.random.uniform([3,],minval=0,maxval=10,dtype=tf.int32,seed=10))

tf.Tensor([9 3 6], shape=(3,), dtype=int32)
tf.Tensor([9 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [74]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=10,  dtype=tf.int32,   seed=10))

tf.Tensor([9 3 6], shape=(3,), dtype=int32)
tf.Tensor([9 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [75]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0,maxval=10,dtype=tf.int32))

tf.Tensor([0 1 8], shape=(3,), dtype=int32)
tf.Tensor([7 4 0], shape=(3,), dtype=int32)
tf.Tensor([9 6 5], shape=(3,), dtype=int32)
tf.Tensor([3 9 1], shape=(3,), dtype=int32)


In [76]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0, maxval=10, dtype=tf.int32))
print(tf.random.uniform([3,], minval=0, maxval=10,dtype=tf.int32))

tf.Tensor([0 1 8], shape=(3,), dtype=int32)
tf.Tensor([7 4 0], shape=(3,), dtype=int32)
tf.Tensor([9 6 5], shape=(3,), dtype=int32)
tf.Tensor([3 9 1], shape=(3,), dtype=int32)


: 

- Cast fuction