### Indexing

In [1]:
import tensorflow as tf

In [13]:
tensorIndexed=tf.constant([0,1,2,3,4,5])
print(tensorIndexed[0:4])
print(tensorIndexed[-4:][::-1])
print(tensorIndexed[-4:])

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([5 4 3 2], shape=(4,), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [30]:
tensorIndexed_two_d = tf.constant([[1,2,3,4],[5,6,7,8],[1,2,3,0],[5,6,7,47]])
print(tensorIndexed_two_d)
print(tensorIndexed_two_d[0])
print(tensorIndexed_two_d[2])
print(tensorIndexed_two_d[:3,:3])
print(tensorIndexed_two_d[2,-1])



tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  2  3  0]
 [ 5  6  7 47]], shape=(4, 4), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 2 3 0], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [5 6 7]
 [1 2 3]], shape=(3, 3), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [40]:
tensorIndexed_three_d = tf.constant(
    [[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 0], [5, 6, 7, 47]]])
print(tensorIndexed_three_d)
print(tensorIndexed_three_d[0,:,:])
print(tensorIndexed_three_d[0,1,:])
print(tensorIndexed_three_d[0,1,2])
print(tensorIndexed_three_d[1,1,3])
print(tensorIndexed_three_d[1,0,3])
print(tensorIndexed_three_d[0,1,3])
print(tensorIndexed_three_d[0:2,...,3])
print(tensorIndexed_three_d[0:2,...,0:2])

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  0]
  [ 5  6  7 47]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(47, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(
[[ 4  8]
 [ 0 47]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [5 6]]

 [[1 2]
  [5 6]]], shape=(2, 2, 2), dtype=int32)


In [48]:
tensorIndexed_four_d = tf.constant(
    [
        [[[1, 2, 3, 4], [5, 6, 7, 8]], 
     
        [[11, 32, 36, 90], [52, 63, 237, 347]]],
        [[[13, 22, 33, 14], [54, 16, 47, 38]],

         [[111, 432, 336, 910], [252, 463, 2437, 3447]]],
     ])
print(tensorIndexed_four_d)
print(tensorIndexed_four_d[0,0,0,0])
print(tensorIndexed_four_d[0,:,:,:])
print(tensorIndexed_four_d[1,1,:,:])
print(tensorIndexed_four_d[1,1,1,:])
print(tensorIndexed_four_d[1,1,1,3])

tf.Tensor(
[[[[   1    2    3    4]
   [   5    6    7    8]]

  [[  11   32   36   90]
   [  52   63  237  347]]]


 [[[  13   22   33   14]
   [  54   16   47   38]]

  [[ 111  432  336  910]
   [ 252  463 2437 3447]]]], shape=(2, 2, 2, 4), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[[[  1   2   3   4]
  [  5   6   7   8]]

 [[ 11  32  36  90]
  [ 52  63 237 347]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[ 111  432  336  910]
 [ 252  463 2437 3447]], shape=(2, 4), dtype=int32)
tf.Tensor([ 252  463 2437 3447], shape=(4,), dtype=int32)
tf.Tensor(3447, shape=(), dtype=int32)
