### TensorFlow Math Operations
- abs function 
- sqrt
- MDAS
- divide_no_nan function (use when we have a ininity)
- math.argmax (return position of the largest value)
- math.argmin (return position of the smallest value)
- math.maximum (return )
- math.minimum
- equal (output boolean whether two tensors for each value are equal or not)
- pow
- reduce_sum
- reduce_max
- reduce_min
- reduce_mean
- reduce_std
- sigmoid
- top_k

In [2]:
import tensorflow as tf

In [3]:
absFun=tf.math.abs(
    [12,-3,2.6,-90.4], name=None
)
absFun

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([12. ,  3. ,  2.6, 90.4], dtype=float32)>

In [4]:
sqrtFun=tf.math.sqrt([9,7,43,32,0.6])
sqrtFun

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([3.       , 2.6457512, 6.5574384, 5.656854 , 0.7745967],
      dtype=float32)>

- Multiply
- DIVide
- Add
- Subtract

In [9]:
add=tf.math.add(
    5, 6, name=None
)
add

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [10]:
add=tf.math.add(
    [6,7,8,133], [63,24,43,23], name=None
)
add

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 69,  31,  51, 156], dtype=int32)>

In [14]:
x=tf.constant([0,1,2,4,34,33])
y=tf.constant([320,124,242,424,324,323])
add=tf.math.add(
    x, y, name=None
)
add

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([320, 125, 244, 428, 358, 356], dtype=int32)>

In [18]:
x=tf.constant([[0,1,2,4,34,33],[13,13,132,424,321,323]])
y=tf.constant([[320,124,242,424,324,323],[0,1,2,4,34,33]])
z=tf.constant([[320,124,242,424,324,323],[0,1,2,4,34,33]])
add=tf.math.add(
    x, y, name=None
)
add

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[320, 125, 244, 428, 358, 356],
       [ 13,  14, 134, 428, 355, 356]], dtype=int32)>

In [19]:
x = [1, 2, 3, 4, 5]
y = 1
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [20]:
x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(1)
x + y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [21]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [22]:
x = tf.constant([1, 2], dtype=tf.int8)
y = [2**7 + 1, 2**7 + 2]
tf.add(x, y)

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>