## Linear Algebra Operations

- multiply

In [1]:
import tensorflow as tf

In [2]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[7,8,9],[10,11,12],[13,14,15]])
MLAs=tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)
MLAs

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186]], dtype=int32)>

In [3]:
a@b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186]], dtype=int32)>

In [4]:
tf.transpose(MLAs)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 66, 156],
       [ 72, 171],
       [ 78, 186]], dtype=int32)>

In [5]:
## 3D matrix multiplication
## several two-d  tensors  combine to  form three-d tensors
a=tf.constant([
    [[1,2,3],
     [6,7,8]],
    [[6,8,1],
     [7,7,2]]
]
)
a=tf.constant([
    [[11,23,34],
     [64,73,18]],
    [[64,82,1],
     [71,7,22]],
    [[4,2,12],
     [17,1,22]],
]
)
print(a@b)
threeD=tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)
print(threeD)

tf.Tensor(
[[[ 749  817  885]
  [1412 1567 1722]]

 [[1281 1428 1575]
  [ 853  953 1053]]

 [[ 204  222  240]
  [ 415  455  495]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 749  817  885]
  [1412 1567 1722]]

 [[1281 1428 1575]
  [ 853  953 1053]]

 [[ 204  222  240]
  [ 415  455  495]]], shape=(3, 2, 3), dtype=int32)


- band_part
  (copy  a tensor setting everything outside a central band  in each innermost matrix to zero.)
  -  tf.linalg.band_part(input, 0, -1) ==> Upper triangular part.
  -  tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
  -   tf.linalg.band_part(input, 0, 0) ==> Diagonal.

In [12]:
# in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)
input=tf.constant([[ 0,  1,  2],
               [-1,  9,  1],
               [-2, -1,  0]])

lower = 1
upper = -1
m =0
n= 1

# ((m-n) <= num_lower)) && ((n-m) <= num_upper)
print(tf.linalg.band_part(input, 0, 0))
# [[0, 0, 0],
# [0, 9, 0]
# [0, 0, 0]]


print(tf.linalg.band_part(input, 1, -1))
# [[0, 0, 0],
#  [-1, 0, 0],
#  [0, -1, 0]]

print(tf.linalg.band_part(input, 2, 1))

tf.Tensor(
[[0 0 0]
 [0 9 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 0  1  2]
 [-1  9  1]
 [ 0 -1  0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 0  1  0]
 [-1  9  1]
 [-2 -1  0]], shape=(3, 3), dtype=int32)


### Most useful Remaining functions below
- cholesky
- cross 
- det
- inverse ( rows should be equal to columns)
- svd
- trace
- einsum

In [15]:
input=tf.constant([[0,  1,  2],
             [-1,  9,  1],
             [-2, -1,  0]], dtype=float)
s,u,v=tf.linalg.svd(input)
print(s)
print(u)
print(v)

tf.Tensor([9.2274275 2.092185  1.8647555], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.13652577  0.02242501  0.99038285]
 [ 0.9867304  -0.09177202 -0.13394435]
 [-0.08788571 -0.9955276   0.03465671]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.08788569  0.9955275   0.03465896]
 [ 0.98673034  0.0917723  -0.13394411]
 [ 0.13652578 -0.0224273   0.9903827 ]], shape=(3, 3), dtype=float32)
