## Linear Algebra Operations

- multiply

In [1]:
import tensorflow as tf

In [6]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[7,8,9],[10,11,12],[13,14,15]])
MLAs=tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)
MLAs

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186]], dtype=int32)>

In [7]:
a@b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 66,  72,  78],
       [156, 171, 186]], dtype=int32)>

In [9]:
tf.transpose(MLAs)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 66, 156],
       [ 72, 171],
       [ 78, 186]], dtype=int32)>

In [12]:
## 3D matrix multiplication
## several two-d  tensors  combine to  form three-d tensors
a=tf.constant([
    [[1,2,3],
     [6,7,8]],
    [[6,8,1],
     [7,7,2]]
]
)
a=tf.constant([
    [[11,23,34],
     [64,73,18]],
    [[64,82,1],
     [71,7,22]],
    [[4,2,12],
     [17,1,22]],
]
)
print(a@b)
threeD=tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)
print(threeD)

tf.Tensor(
[[[ 749  817  885]
  [1412 1567 1722]]

 [[1281 1428 1575]
  [ 853  953 1053]]

 [[ 204  222  240]
  [ 415  455  495]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 749  817  885]
  [1412 1567 1722]]

 [[1281 1428 1575]
  [ 853  953 1053]]

 [[ 204  222  240]
  [ 415  455  495]]], shape=(3, 2, 3), dtype=int32)


- band_part
  (copy  a tensor setting everything outside a central band  in each innermost matrix to zero.)