### Agenda
- Ragged Tensor
- Sparse Tensors
- String Tensors
- Variables

In [2]:
import tensorflow as tf

In [7]:
# rf.ragged help in dealing with non rectangular shape tensors
tensorTD=[[1,2,3,4],[9,32,43,53],[24,],[25,18,],[1,2,3,4,5,6,7,8,9]]
raggedtensor=tf.ragged.constant(tensorTD)
print(raggedtensor.shape)
print(raggedtensor)


(5, None)
<tf.RaggedTensor [[1, 2, 3, 4], [9, 32, 43, 53], [24], [25, 18],
 [1, 2, 3, 4, 5, 6, 7, 8, 9]]>


In [ ]:
# tf.raged.boolean_mask applies to boolean mask to data without flattening the mask dimensions


In [17]:
## raggedtensor.from_nested_row_lengths is used 
print(tf.RaggedTensor.from_row_lengths(values=[3,1,4,1,5,9,2,6],
                                       row_lengths=[4,0,3,1,0]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
## sparse tensor 
sparsetensor=tf.sparse.SparseTensor(
    [[1,1],
    [3,4]], values=[11,56], dense_shape=[5,6]
)


In [20]:
tf.sparse.to_dense(sparsetensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

### string tensors

In [21]:
## string tensors 
tensor_string=tf.constant(["hello", "world","my name","is","wajhat"])
print(tensor_string)

tf.Tensor([b'hello' b'world' b'my name' b'is' b'wajhat'], shape=(5,), dtype=string)


In [22]:
tf.strings.join(tensor_string,separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world my name is wajhat'>

In [23]:
tf.strings.length(tensor_string)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 5, 7, 2, 6], dtype=int32)>

### Tensor Variables

In [29]:
oneD=tf.constant([1,2])
x_var=tf.Variable(oneD)
x_var.assign_sub([0,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

In [30]:
x_var.assign_add([5,7])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 8], dtype=int32)>

: 